### ISSUE TITLE
'get input' function

### ISSUE THREAD

**Issue by iandronis** [CodeClub4/ChessAI#6]
We will make the assumption that the user will give her/his next move following this format:
```
ex. "e2,e4"
```
, meaning she/he will move her/his piece from square 'e2' to 'e4'.

So, what we want to do is:
- [ ] {part_1} new function 'get_input()': get a string text from the user
- [ ] {part_2} convert the chess coordinates (ex. "e2,e4") into our board, array coordinates (ex. 41, 43)

**Comment by TheraOzz** [comment]
closed due to another updated PR
